### ISSUE TITLE
Wrong pluralization handling

### ISSUE THREAD

**Issue by derSascha** [aderyabin/localer#7]
In some languages a word needs pluralization, but may be not in another.

Considering this translations from the [rails-i18n gem](https://github.com/svenfuchs/rails-i18n):
```
en:
  number:
    human:
      decimal_units:
        units:
          billion: Billion
```
and
```
de:
  number:
    human:
      decimal_units:
        units:
          billion:
            one: Milliarde
            other: Milliarden
```
results in a localer error:
```
Missing translations found (...):
* de.number.human.decimal_units.units.billion
* en.number.human.decimal_units.units.billion.one
* en.number.human.decimal_units.units.billion.other
```

Any plans to support this?
